#!/usr/bin/env bash
#It displays the content of the file /etc/passwd, using the while loop + IFS.
while read -r line
do 


echo "The user $(cut -d: -f1 <<< "$line") is part of the $(cut -d: -f4 <<< "$line")  gang, lives in $(cut -d: -f6 <<< "$line") and rides $(cut -d: -f7 <<< "$line"). $(cut -d: -f3 <<< "$line")'s place is protected by the passcode $(cut -d: -f2 <<< "$line"),  more info about the user here: $(cut -d: -f5 <<< "$line")"





done < /etc/passwd
