#!/usr/bin/env bash
#It displays "bad luck" for the 4th loop iteration, "good luck" for the 8th, and "Best School" for all the other iterations
i=1
while [ $i -le 10 ]
do 
if [ $i -eq 4 ]
then
  echo 'bad luck'
elif [ $i -eq 8 ]
then
  echo 'good luck'
else
  echo 'Best School'
fi
i=$((i+1))
done

