#!/usr/bin/env bash
#This script manages the process using arguments such as start, stop, and restart
case "$1" in 
	start) 
		./manage_my_process &
		echo "$$" > /var/run/my_process.pid
		echo 'manage_my_process started'
		;;
	stop)
		killall 11-manage_my_process
		rm /var/run/my_process.pid
		echo 'manage_my_process stopped'
		;;
	restart)
		killall 11-manage_my_process
		rm /var/run/my_process.pid
		./manage_my_process &
		echo "$$" > /var/run/my_process.pid
		echo 'manage_my_process restarted'
		;;
	*)
		echo 'Usage: manage_my_process {start|stop|restart}'
		exit 1
		;;
esac
