#!/usr/bin/env bash
#It displays To infinity and beyond indefinitely with a sleep 2 in between each iteration. Also it displays I am invincible!!! when receiving a SIGTERM signal
while :
do
	echo "To infinity and beyond"
	trap "echo 'I am invincible'" SIGTERM
	sleep 2 
done

